#!/usr/bin/env python3
"""
Simulates how Claude Desktop would interact with the MCP-PDF server
when a user asks to create a PDF with an image from a URL.
"""

import json
from mcp_pdf.server import MCPPDFServer


async def simulate_claude_desktop_request():
    """
    Simulate a request from Claude Desktop to create a PDF with an image URL.

    This demonstrates the exact workflow:
    1. User in Claude Desktop: "Create a PDF with this image: https://picsum.photos/800/600"
    2. Claude calls the generate_pdf tool with the image URL
    3. Server downloads the image and creates the PDF
    4. Server returns the path to the generated PDF
    """

    print("=" * 80)
    print("SIMULATING CLAUDE DESKTOP REQUEST")
    print("=" * 80)
    print()

    # This is what Claude Desktop would send to the MCP server
    print("📥 USER REQUEST (in Claude Desktop):")
    print("-" * 80)
    print("User: 'Create a technical document with this diagram:")
    print("      https://picsum.photos/800/600'")
    print()

    print("📤 CLAUDE DESKTOP CALLS MCP SERVER:")
    print("-" * 80)
    print("Tool: generate_pdf")
    print("Arguments:")

    # This is the exact JSON that Claude Desktop sends to the MCP server
    request = {
        "document_spec": {
            "title": "Technical Documentation",
            "theme": {},  # Use default theme
            "pages": [
                {
                    "page_type": "title",
                    "title": "Technical Documentation",
                    "subtitle": "System Architecture Overview",
                    "author": "Generated by Claude",
                    "date": "November 2024"
                },
                {
                    "page_type": "diagram",
                    "title": "System Architecture",
                    "image": "https://picsum.photos/800/600",  # Image URL!
                    "description": [
                        "High-level system architecture",
                        "Shows main components and interactions",
                        "Updated: November 2024"
                    ]
                },
                {
                    "page_type": "content",
                    "title": "Overview",
                    "content": [
                        {
                            "type": "text",
                            "text": "This document describes our system architecture."
                        },
                        {
                            "type": "bullet",
                            "items": [
                                "Scalable microservices architecture",
                                "Event-driven communication",
                                "Cloud-native deployment"
                            ]
                        }
                    ]
                }
            ],
            "output": {
                "filename": "technical_doc.pdf",
                "directory": "./output"
            }
        }
    }

    print(json.dumps(request, indent=2))
    print()

    print("🔧 MCP SERVER PROCESSING:")
    print("-" * 80)
    print("1. ✓ Parsing document specification")
    print("2. ✓ Detecting image URL: https://picsum.photos/800/600")
    print("3. ✓ Downloading image from URL...")
    print("4. ✓ Generating PDF with downloaded image")
    print("5. ✓ Cleaning up temporary files")
    print()

    # Actually generate the PDF using the server's PDF generator
    from mcp_pdf.models.document_spec import DocumentSpec
    from mcp_pdf.rendering.pdf_generator import PDFGenerator

    doc_spec = DocumentSpec.model_validate(request["document_spec"])
    generator = PDFGenerator()
    result = generator.generate_pdf(doc_spec)

    print("📤 MCP SERVER RESPONSE:")
    print("-" * 80)
    print(json.dumps(result, indent=2))
    print()

    print("💬 CLAUDE DESKTOP RESPONSE TO USER:")
    print("-" * 80)
    if result['ok']:
        print(f"✅ I've created your technical documentation PDF!")
        print(f"📄 Location: {result['output']}")
        print(f"📊 Pages: {result['pages_generated']}")
        print()
        print("The PDF includes:")
        print("  - Title page with your specifications")
        print("  - System architecture diagram (downloaded from URL)")
        print("  - Overview page with system description")
    else:
        print(f"❌ Error: {result.get('error', 'Unknown error')}")
    print()

    print("=" * 80)
    print("✅ SIMULATION COMPLETE")
    print("=" * 80)
    print()
    print("This demonstrates the complete workflow:")
    print("  1. User provides image URL in Claude Desktop chat")
    print("  2. Claude formats it as a generate_pdf tool call")
    print("  3. MCP server receives the request")
    print("  4. Server downloads image from URL")
    print("  5. Server embeds image in PDF")
    print("  6. Server returns success response with file path")
    print("  7. Claude informs user where the PDF was saved")
    print()
    print(f"📄 Generated PDF: {result['output']}")
    print()


if __name__ == "__main__":
    import asyncio
    asyncio.run(simulate_claude_desktop_request())
